### ISSUE TITLE
Displaying module on top_right is displaying as full width

### ISSUE THREAD

**Issue by poonasor** [michael5r/mmm-nest-cameras#3]
I've set the camerasPerRow to 1 and displaying it on the top_right, following the setup guild but its displaying as the full width.

Any suggestions on how I can display it on the top_right that it takes up 1/3 of the screen would be greatly appreciated.

Great work on the module!
Thank you.

**Comment by michael5r** [comment]
@poonasor Sure - just add the following to your `custom.css` file:

```css
.mmm-nest-cameras .module-content {
    width: 300px;
}
```
You can change the `300px` to whatever works for the size of your screen.

The reason you have to add a width like this is because the Magic Mirror system doesn't actually assign widths to any of the narrow columns (the `left` and `right` ones) - people are meant to do that themselves, based on the width of the screen they're using.
